logging:
    level:
#        tk.mybatis: DEBUG
        com.emrubik.springcloud.auth: DEBUG
spring:
    application:
        name: springcloud-auth
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
#    datasource:
#        name: test
#        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ag_admin_v1?useUnicode=true&characterEncoding=UTF8
#        username: root
#        password: 123456
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
    zipkin:
        enabled: true
    sleuth:
      sampler:
#        percentage: 1
#mybatis:
#    basepackage: com.github.wxiaoqi.security.admin.mapper
#    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 9777

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000

jwt:
  token-header: Authorization
  rsa-secret: xx1WET12^%3^(WE45
  expire: 3600

#redis-cache 相关
#redis:
#    pool:
#         maxActive: 300
#         maxIdle: 100
#         maxWait: 1000
#    host: ${REDIS_HOST:localhost}
#    port:  ${REDIS_PORT:6379}
#    password:
#    timeout: 2000
#    # 服务或应用名
#    sysName: ace-admin
#    enable: true
#    database: 0